apiVersion: v1
kind: Secret
metadata:
  name: token-jwt-secret
type: Opaque
data:
  jwt_secret: bWljcm9zZXJ2aWNlLXRlc3Q=
  jwt_refresh_secret: bWljcm9zZXJ2aWNlLXRlc3QtcmVmcmVzaA==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: scys12/microservice-test-gateway:1.0
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: USER_SERVICE_URL
              value: "http://userservice"
            - name: TOKEN_SERVICE_URL
              value: "http://tokenservice"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: token-jwt-secret
                  key: jwt_secret
            - name: JWT_REFRESH_SECRET
              valueFrom:
                secretKeyRef:
                  name: token-jwt-secret
                  key: jwt_refresh_secret
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  type: ClusterIP
  selector:
    app: gateway
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-external
spec:
  type: LoadBalancer
  selector:
    app: gateway
  ports:
    - name: http
      port: 80
      targetPort: 8080
